//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBBABA.Infra.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class solnascenteEntities : DbContext
    {
        public solnascenteEntities()
            : base("name=solnascenteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBAtleta> TBAtletas { get; set; }
        public virtual DbSet<TBCategoria> TBCategorias { get; set; }
        public virtual DbSet<TBMensalidade> TBMensalidades { get; set; }
        public virtual DbSet<TBRegistro> TBRegistroes { get; set; }
        public virtual DbSet<TBSituacao> TBSituacaos { get; set; }
        public virtual DbSet<TBTipoPagamento> TBTipoPagamentoes { get; set; }
    }
}
