//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBBABA.Infra.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.ModelConfiguration.Conventions;

    public partial class solnascenteEntities : DbContext
    {
        public solnascenteEntities()
            : base("name=solnascenteEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //não pluraliza o nome das tabelas
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

            //não deleta em cascate
            modelBuilder.Conventions.Remove<OneToManyCascadeDeleteConvention>();
            modelBuilder.Conventions.Remove<ManyToManyCascadeDeleteConvention>();

            //define que qualquer coisa com IdAlgumacoisa seja uma primaryKey
            modelBuilder.Properties().Where(p => p.Name == p.ReflectedType.Name + "Id")
            .Configure(p => p.IsKey());

            //define que tudo que string na converão seja varchar
            modelBuilder.Properties<string>()
            .Configure(p => p.HasColumnType("varchar"));

            //define um varchar de 100 caracteres como padrão
            modelBuilder.Properties<string>()
            .Configure(p => p.HasMaxLength(100));
        }

    public virtual DbSet<TBAtleta> TBAtleta { get; set; }
    public virtual DbSet<TBCategoria> TBCategoria { get; set; }
    public virtual DbSet<TBMensalidade> TBMensalidade { get; set; }
    public virtual DbSet<TBRegistro> TBRegistro { get; set; }
    public virtual DbSet<TBSituacao> TBSituacao { get; set; }
    public virtual DbSet<TBTipoPagamento> TBTipoPagamento { get; set; }
    }
}
