//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBBABA.Infra.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBAtleta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBAtleta()
        {
            this.TBMensalidades = new HashSet<TBMensalidade>();
        }
    
        public int idAtleta { get; set; }
        public string nomeAtleta { get; set; }
        public string sobrenomeAtleta { get; set; }
        public string apelidoAtleta { get; set; }
        public Nullable<int> coleteNumeroAtleta { get; set; }
        public Nullable<System.DateTime> nascimentoAtleta { get; set; }
        public int idSituacaoAtleta { get; set; }
        public string telefoneAtleta { get; set; }
        public Nullable<System.DateTime> dataCadastroAtleta { get; set; }
        public Nullable<int> posicaoAtleta { get; set; }
        public Nullable<int> comissaoAtleta { get; set; }
    
        public virtual TBSituacao TBSituacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBMensalidade> TBMensalidades { get; set; }
    }
}
