//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBBABA.Infra.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCategoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBCategoria()
        {
            this.TBRegistro = new HashSet<TBRegistro>();
        }
    
        public int idCategoria { get; set; }
        public string nomeCategoria { get; set; }
        public Nullable<System.DateTime> dataCadastroCategoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBRegistro> TBRegistro { get; set; }
    }
}
