//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBBABA.Infra.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBRegistro
    {
        public int idRegistro { get; set; }
        public int idMensalidadeRegistro { get; set; }
        public string nomeCredorRegistro { get; set; }
        public Nullable<int> idNomeAtleta { get; set; }
        public System.DateTime dataCadastroRegistro { get; set; }
        public int idTipoPagamentoRegistro { get; set; }
        public int idCategoriaRegistro { get; set; }
        public string observacaoRegistro { get; set; }
        public System.DateTime dataPagamento { get; set; }
        public string valorPagamento { get; set; }
        public string valorDesconto { get; set; }
        public string valorSaldo { get; set; }
    
        public virtual TBCategoria TBCategoria { get; set; }
        public virtual TBMensalidade TBMensalidade { get; set; }
        public virtual TBTipoPagamento TBTipoPagamento { get; set; }
    }
}
