//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBBABA.Infra.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSituacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBSituacao()
        {
            this.TBAtleta = new HashSet<TBAtleta>();
        }
    
        public int idSituacao { get; set; }
        public string nomeSituacao { get; set; }
        public Nullable<System.DateTime> dataCastrodoSituacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBAtleta> TBAtleta { get; set; }
    }
}
